name: Sample Request
description: Request a new sample project for the ADK-TS showcase
labels: ["sample-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new ADK-TS sample project!

  - type: textarea
    id: description
    attributes:
      label: Sample Description
      description: What kind of sample project would you like to see?
      placeholder: I'd like to see an sample that demonstrates...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any specific features, use cases, or technologies you'd like included?
      placeholder: This sample should show how to... It would be helpful to include...
    validations:
      required: false
